### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by vext01**
There are two commits on the end of this sync which you should take a look at.

 - One to remove STD_TRACER_MODE related bits for now.
 - One reverts priming from the last PR (oops).

### CODE REVIEW

**Comment by ltratt** [comment]
Do you need to squash at all?

**Comment by vext01** [comment]
No squashing required. Thanks

**Comment by ptersilie** [comment]
Do you not need to squash the "undo priming commit"?

**Comment by vext01** [comment]
It doesn't really make sense to squash it into the other commits. Let's leave it separate.

**Pull request merged**
