### PR TITLE
Reflect changes in ykpack for querying a function's body flags.

### LINKED ISSUE #158: Abstract bodyflags in SIR.
* Make a function to check membership of a flag in the bitfield (thus allowing the underlying representation to change).
 * Maybe use the `bitflags` crate (but check if it's worth bringing in more deps. A bitfield is so simple, it may not be worth it).

### PR DESCRIPTION
**Pull request by ltratt**
See https://github.com/softdevteam/yk/pull/161.

ci-yk: ltratt remove_bit_ops

Fixes https://github.com/softdevteam/yk/issues/158#issuecomment-734200137.

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
The build failed the first time because I wrote `ci-yk` without a `:`. Mea culpa!

**Comment by vext01** [comment]
This is our friend https://github.com/rust-lang/rust/pull/79375

I'll kill the files on the CI server and try again.

**Pull request merged**
