### PR TITLE
Faster sir decoding

### PR DESCRIPTION
**Pull request by bjorn3**
Companion PR of softdevteam/yk#116

### CODE REVIEW

**Comment by vext01** [comment]
bors try

**Comment by bjorn3** [comment]
bors try-

**Comment by bjorn3** [comment]
There was an error I missed in the yk PR. I have now fixed it.

**Comment by vext01** [comment]
bors try

**Comment by bjorn3** [comment]
Updated the list of allowed dependencies.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
Please update the dep override and lock file and squash.

**Comment by bjorn3** [comment]
Done

Edit: missed something

**Comment by bjorn3** [comment]
Forgot to squash the commits. Done.

**Pull request merged**
