### PR TITLE
Add lowering for bool constants

### PR DESCRIPTION
**Pull request by ptersilie**
Requires 3-way merge together with https://github.com/softdevteam/yk/pull/54.

### CODE REVIEW

**Comment by ptersilie** [comment]
I have a rebase and 3-way merge commit ready to be pushed, so let me know when you are ready.

**Comment by vext01** [comment]
(This is all fine)

**Comment by ptersilie** [comment]
Cycle breaker added.

**Comment by ptersilie** [comment]
Tidy checks failed. Fixing.

**Comment by ptersilie** [comment]
Wait, it's the license of ykpack. I thought I fixed this.

**Comment by ptersilie** [comment]
Ah, I didn't rebase the yk repo. Fixing.

**Comment by ptersilie** [comment]
Fixed. Okay to squash? Then we can try again.

**Comment by vext01** [comment]
go ahead

**Comment by ptersilie** [comment]
Squashed. Let's try again!

**Pull request merged**
