### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by vext01**
An inoffensive sync with upstream.

### CODE REVIEW

**Comment by vext01** [comment]
> dependency `ykpack 0.1.0 (git+https://github.com/softdevteam/yk#b8322417112710efd79bb968ce3f6eb77197f645)` does not define a license expression

I guess it doesn't check that when you use a filesystem path. Will fix.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
> error: internal compiler error: cannot lex `source_file` without source: /home/buildbot-worker8/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.6/src/x86_64/mod.rs

**Comment by bjorn3** [comment]
That is https://github.com/rust-lang/rust/issues/69933, which was fixed by https://github.com/rust-lang/rust/pull/70172.

**Comment by vext01** [comment]
> That is rust-lang/rust#69933, which was fixed by rust-lang/rust#70172.

Thanks! I'll re-sync tomorrow.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
Right, good. I've used `git --rebase-merges` to put that commit that I cherry-picked inside the merge commit. I also squashed the lock update into the merge.

Sound good? If so I will force-push.

(It was not easy...)

**Comment by ltratt** [comment]
Since Lukas was already happy with this, please force push.

**Comment by vext01** [comment]
There we go. Fingers crossed.

**Comment by vext01** [comment]
I missed a bit. Can I squash it in?

**Comment by ptersilie** [comment]
Looks good to me.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
Yay :)

**Pull request merged**
