### PR TITLE
Add a couple of small missing lowerings.

### PR DESCRIPTION
**Pull request by vext01**
These are needed to complete lowering of my dumb example program.

This can also serve as a test for the new buildbot.

### CODE REVIEW

**Comment by ltratt** [comment]
Looks OK to me. You want me to r plus this or ...?

**Comment by vext01** [comment]
Yeah, let's try r+

**Comment by vext01** [comment]
image

:)

**Comment by ltratt** [comment]
The screenshot is of b13?

**Comment by vext01** [comment]
yep!

**Pull request merged**
