### PR TITLE
Remove trace invalidation (for now)

### PR DESCRIPTION
**Pull request by vext01**
We will come back to trace invalidation later, but since the current code is known to be incorrect, remove it.

Also downgrade the atomic bool used to track if we are tracing, to a regular bool. That was only needed for reetrancy with signal handlers.

Another PR will follow for yk.

### CODE REVIEW

**Comment by vext01** [comment]
Hold on. This isn't right still.

**Comment by vext01** [comment]
Ready for review.

**Comment by ptersilie** [comment]
Looks fine. Please squash. While doing so you can also fix the typo "in correct" in the first commit message if you are going to keep that one.

**Comment by vext01** [comment]
Squashed into two commits and fixed typo.

**Comment by vext01** [comment]
Oops, looks like i missed something:
```
error[E0432]: unresolved import `core::yk::swt::invalidate_trace`
  --> /home/buildbot-worker4/worker4/ykrustc-buildbot-build-script-swt/build/src/test/ui/yk_swt/invalidate-trace.rs:22:50
   |
LL | use core::yk::swt::{start_tracing, stop_tracing, invalidate_trace};
   |                                                  ^^^^^^^^^^^^^^^^ no `invalidate_trace` in `yk::swt`
```

**Comment by vext01** [comment]
Removed this test. OK to squash?

**Comment by ptersilie** [comment]
bors try

**Comment by ptersilie** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Pull request merged**
