### PR TITLE
Lower references/dereferences.

### PR DESCRIPTION
**Pull request by ptersilie**
Add lowerings for references and deref projections.

### CODE REVIEW

**Comment by vext01** [comment]
Is there a companion PR?

**Comment by ptersilie** [comment]
Hold your horses, I was just typing it up. :-)

Companion PR here: https://github.com/softdevteam/yk/pull/91

**Comment by vext01** [comment]
Please prime.

**Comment by ptersilie** [comment]
Already primed.

bors try

**Comment by vext01** [comment]
Bors r+

**Pull request merged**
