### PR TITLE
Lower index projections.

### PR DESCRIPTION
**Pull request by ptersilie**
Companion PR to https://github.com/softdevteam/yk/pull/123

### CODE REVIEW

**Comment by ptersilie** [comment]
Added priming commit. Ok to prime?

**Comment by vext01** [comment]
Go ahead.

**Comment by ptersilie** [comment]
bors try

**Comment by ptersilie** [comment]
bors try

**Comment by vext01** [comment]
If you backout the dep override and update the lock file, this can go in.

**Comment by ptersilie** [comment]
Done.

**Pull request merged**
