### PR TITLE
Add more SIR integer lowerings.

### PR DESCRIPTION
**Pull request by vext01**
Lowerings required for https://github.com/softdevteam/yk/pull/68

### CODE REVIEW

**Comment by ptersilie** [comment]
This looks good.

**Comment by ptersilie** [comment]
This needs a commit that changes the dependencies to this https://github.com/softdevteam/yk/pull/68, so we can manually built this on buildbot. Then we can merge https://github.com/softdevteam/yk/pull/68 and afterwards reverse this commit and merge this.

**Comment by vext01** [comment]
Updating cached ykrustc in CI.

bors try

**Comment by vext01** [comment]
OK to squash?

**Comment by ptersilie** [comment]
Yes, please squash.

**Comment by vext01** [comment]
Splat.

**Pull request merged**
