### PR TITLE
Sync upstream.

### PR DESCRIPTION
**Pull request by vext01**
Sync upstream.

Since the [DeclareMethods trait is now gone](https://github.com/rust-lang/rust/commit/0bc405e3521d84cfaef7d94f1ae40c6c16796c8b), we needed to find a new home for our Sir methods.

I've made a `SirMethods` trait which the codegen requires. See the last commit. If it looks OK I'll squash it in.

CC @bjorn3 as he's worked on `DeclareMethods` in ykrustc recently.

All tests (here and in `yk`) passing.

### CODE REVIEW

**Comment by vext01** [comment]
Gah, upstream CI is running again.

**Comment by vext01** [comment]
We need to get into the habit of removing `.github` when syncing.

**Comment by bjorn3** [comment]
> We need to get into the habit of removing .github when syncing.

https://github.com/softdevteam/ykrustc/settings/actions has an option to disable github actions completely.

image

**Comment by vext01** [comment]
Thanks done.

Does the `SirMethods` trait look OK?

**Comment by bjorn3** [comment]
Yes

**Comment by vext01** [comment]
Thanks!

**Comment by ptersilie** [comment]
Looks good. Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
