### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by vext01**
This syncs ykrustc with todays upstream master.

Although there's 3690 commits, there's really only two:
 * The merge (including resolution of conflicts).
 * Stuff I had to then do to make it build and test (fbeb8abd32).

The latter is probably worth a quick skim, but the former is unreviewable.

(This was quite a difficult sync)

### CODE REVIEW

**Comment by vext01** [comment]
I was unable to repro that failure, and it looks unrelated to us anyway.

I've merged in upstream again. Let's retry?

**Comment by vext01** [comment]
The problem was, `.buildbot.sh` sets `RUST_BACKTRACE`, which interferes with the test outputs.

Removed.

OK to squash?

**Comment by vext01** [comment]
Wait, squashing doesn't really make sense here. I will re-word the previous commit message though, if that's ok.

**Comment by ltratt** [comment]
Please go ahead.

**Comment by vext01** [comment]
Done. Bors away.

**Comment by vext01** [comment]
That build took 2h40m :)

**Pull request merged**
