### PR TITLE
Yk sync 20200904

### PR DESCRIPTION
**Pull request by vext01**
This syncs upstream.

I've left a couple of commits on the end for review. I'll squash them later.

@bjorn3 Do you know why `deps.rs` needs to diverge from upstream (final commit), other than the new deps we added of course? Weird, right?

Works with yk, and all tests pass.

### CODE REVIEW

**Comment by bjorn3** [comment]
The `Cargo.lock` seems to have changed a lot. (https://github.com/softdevteam/ykrustc/compare/ef55a0a92f3cb6572ef67d99f4aefbdeb7b6b804...b821f14b02cbb4dd423ac9ceb7354537982a42a1) Try resetting `Cargo.lock` to the one of ef55a0a92f3cb6572ef67d99f4aefbdeb7b6b804.

**Comment by ptersilie** [comment]
The deps diff looks weird (it mostly changes comments) or is it just because it hasn't been squashed yet. Otherwise looks fine.

**Comment by vext01** [comment]
The deps change is mostly the doing of `x.py fmt`, but there are other changes.

Will try @bjorn3's suggestion.

**Comment by vext01** [comment]
That worked!

**Comment by vext01** [comment]
OK to squash?

**Comment by ptersilie** [comment]
Please do.

**Comment by vext01** [comment]
splat

**Pull request merged**
