### PR TITLE
Disable block merging for constant assertions in the LLVM backend.

### PR DESCRIPTION
**Pull request by vext01**
This prevents one case of block merging in the Rust compiler.

There may be more, but I have not found them yet!

I opted to keep this separate from the last PR to simplify reviewing.

Check the base branch.

### CODE REVIEW

**Comment by ltratt** [comment]
It's not clear from the code: is this merging 2 MIR blocks into 1 MIR blocks or 2 LLVM blocks into 1 LLVM block?

**Comment by vext01** [comment]
Upon re-visiting this, I think I've slightly misunderstood. It's not merging anything at all.

It changes this:
```
    /---- B_2
B_1
    \---- B_3
```

To:

```
B_1 -> B_2
```

If it knows that the assertion can never cause `B_3` to be reachable. In this case, `B_3` is not code-genned at all.

I think we do still want to disable this, so that the structure of the binary is the same as the MIR, but the wording of the comment and commit message need to be revised.

(sorry).

**Comment by ltratt** [comment]
I don't think we need to disable this: all it means is that a MIR block *x* won't have a label *x* in the binary. But that's equivalent to having a label *x* in the binary and never PTing it.

**Comment by vext01** [comment]
I think I've just come to the same conclusion myself...

Shall we move on *without* it and maybe revisit it if there's evidence that this is indeed a problem for us? In my eyes, the smaller the divergence from upstream the better!

**Comment by ltratt** [comment]
Yes, I'd prefer to have the fewest changes we can get away with. So let's close this?

**Comment by vext01** [comment]
(sorry for the noise)

**Pull request closed without merging**
