### PR TITLE
Serialise the number of args for bodies.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/softdevteam/yk/pull/111

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]

**Comment by vext01** [comment]
Priming the CI.

bors try.

**Comment by vext01** [comment]
I think this is good to go now.

**Comment by bjorn3** [comment]
Yes, only the CI priming commit needs to be reverted.

**Comment by vext01** [comment]
Force pushed. Also updated lock file.

**Pull request merged**
