### PR TITLE
Sync with upstream Rust.

### PR DESCRIPTION
**Pull request by vext01**
This syncs us with upstream rust via a merge commit.

It's a huge sync, and as such isn't really reviewable I'm afraid.

It was fairly straight forward, just time consuming.

The only thing really of note is that I skipped four more uninteresting tests, which could not be fixed by `#[no_trace]`.

All tests passing now.

Thanks

### CODE REVIEW

**Comment by vext01** [comment]
It's going to take a while for the build to start, as buildbot is slowly importing each commit into it's sqlite database one at a time :P

**Comment by vext01** [comment]
The failure is a gdb test failure. I forgot to install a Python enabled gdb on the dev box (bencher11), so this is probably why I didn't hit this.

Will install gdb and try to repro.

**Comment by ltratt** [comment]
OK, I can do an r plus when you've installed python-gdb?

**Comment by vext01** [comment]
> OK, I can do an r plus when you've installed python-gdb?

**Comment by vext01** [comment]
> OK, I can do an r plus when you've installed python-gdb?

Not yet. The failure is real. The buildbot machine has the correct gdb, just not my dev machine. It's likely that I need to adjust a/some tests.

**Comment by ltratt** [comment]
Ah, OK.

**Comment by vext01** [comment]
I was able to repro after installing a python enabled gdb. It was just that one test.

If you are OK with the commit, we can squash it in and kick bors.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat

**Pull request merged**
