### PR TITLE
Store symbol names into TIR call operands.

### PR DESCRIPTION
**Pull request by vext01**
This is the compiler side change for https://github.com/softdevteam/yk/pull/12

The ykpack change goes in first and then this needs a lock bump.

### CODE REVIEW

**Comment by ltratt** [comment]
This can now be bumped.

**Comment by vext01** [comment]
Like so.

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
