### PR TITLE
Store number of vars per function in SirFuncCx

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by ptersilie** [comment]
Requires a rebase after #102 is merged.

**Comment by ltratt** [comment]
A minor terminology thing: it's fairly common in compilers (and I note that's the case here with `mir_body.local_decls`) to call these "locals". So maybe `num_locals` might be a slightly more idiomatic name? [I don't feel strongly about this, but thought it might be worth mentioning.]

**Comment by ptersilie** [comment]
Good point. Will fix.

**Comment by ltratt** [comment]
@ptersilie Is this ready for rereview?

**Comment by ptersilie** [comment]
Whoops, forgot to assign @vext01 to this. But we are currently blocked on the bors issue anyways.

**Comment by ltratt** [comment]
Well, I'm happy with your change in https://github.com/softdevteam/ykrustc/pull/103/commits/5a24c7f3aca97a088190f349fbc72a67956d5477.

**Comment by ltratt** [comment]
@ptersilie I think this now needs rebasing against master (and, unfortunately, there are a couple of conflicts), and squashing. Once that's done, I think we can now merge!

**Comment by vext01** [comment]
I'm late to the party, but the changes LGTM.

**Comment by ptersilie** [comment]
Had to add one more fix which we'll need to squash later. Though we can do that after we merged https://github.com/softdevteam/yk/pull/65.

**Comment by ptersilie** [comment]
Should I start the merge process?

**Comment by vext01** [comment]
Please go ahead.

**Comment by ptersilie** [comment]
Undid the cycle breaker. Ok to squash?

**Comment by vext01** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed.

**Comment by vext01** [comment]
```
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed
```

Is this a lock file issue?

**Comment by ptersilie** [comment]
Whoops, forgot to push that. Let's try.

bors try

**Comment by vext01** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
