### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by vext01**
This syncs upstream as of 2020-05-07.

Most of the things I had to fix were uninteresting apart from the mir-opt test change.

Our SIR tests used to piggy back on a lot of mir-opt test infrastructure, but they've since changed all of that and removed the ability to elide in expected test outcomes. We have tests that use elision for good reason, so I've forward ported some of the old mir-opt test stuff into our tree.

That stuff is in [runtest_sir.rs](https://github.com/vext01/ykrustc/blob/sync-upstream-2020-05-07/src/tools/compiletest/src/runtest_sir.rs).

Tests are passing, and I also checked `yk` works too.

### CODE REVIEW

**Comment by vext01** [comment]
Looks like bors did something weird

**Comment by ptersilie** [comment]
Try again?

bors r+

**Comment by vext01** [comment]
I guess so

**Comment by ptersilie** [comment]
Hmm, bors doesn't seem to be reacting at all.

**Comment by ptersilie** [comment]
bors ping

**Comment by vext01** [comment]
bors crashed again :\

**Comment by vext01** [comment]
bors try

**Comment by ltratt** [comment]
bors ping

**Comment by vext01** [comment]
reinstalled bors.

bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
Let's try re-raising the PR.

**Pull request closed without merging**
