### PR TITLE
Sync Upstream.

### PR DESCRIPTION
**Pull request by vext01**

### CODE REVIEW

**Comment by vext01** [comment]
Building rustfmt failed.

We might have gotten unlucky, or we might have broken something.

In these cases I tend to merge the latest code and try again.

**Comment by vext01** [comment]
Let's give this a shot. Please retry.

**Comment by vext01** [comment]
After fixing the import, rustfmt still fails.

Will need to look into it tomorrow...

**Comment by vext01** [comment]
image

**Comment by vext01** [comment]
bors try

**Comment by ptersilie** [comment]
Anything to squash or leave as is?

**Comment by vext01** [comment]
squashed.

**Pull request merged**
