### PR TITLE
Sync upstream.

### PR DESCRIPTION
**Pull request by vext01**
Note that in the `fmt-write-bloat` test, we have `# ignore-test broken if debug-assertions set, as in Yorick CI.`

I think that's right. It now skips anyway.

yk tests pass.

### CODE REVIEW

**Comment by bjorn3** [comment]
Diff with upsteam: https://github.com/softdevteam/ykrustc/compare/a118ee2c13cc96ceb27bd5030c1cca1052377604...a2cf80319581eb832195ffd165001f113cb1ec19

bors r+

**Comment by vext01** [comment]
Mind if a force push to fix this?

**Comment by bjorn3** [comment]
Force pushing a fix is fine.

**Comment by vext01** [comment]
splat.

**Pull request merged**
