### PR TITLE
TIR -> SIR.

### PR DESCRIPTION
**Pull request by vext01**
Companion PR to https://github.com/softdevteam/yk/pull/15.

### CODE REVIEW

**Comment by ltratt** [comment]
Does the lock file need updating?

**Comment by vext01** [comment]
It does. Bear with me.

**Comment by vext01** [comment]
Oddly enough, running `cargo check` doesn't change the `Cargo.lock` on this occasion.

I think we can go ahead.

**Comment by vext01** [comment]
```
...
---- [yk-sir] yk-sir/simple_sir.rs stdout ----
thread '[yk-sir] yk-sir/simple_sir.rs' panicked at 'Did not find expected line, error: ran out of mir dump to match against
Expected Line: "[Begin SIR for main]"
Test Name: /home/buildbot-worker8/worker8/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/test/yk-sir/simple_sir/a
Expected:
... (elided)
[Begin SIR for main]
... (elided)
$1: t0 = $2: t0
... (elided)
[End SIR for main]
Actual:
[Begin TIR for main]
...
```

Well this is odd. Here's the line in the diff that should have prevented that failure:
https://github.com/softdevteam/yk/commit/0dc5d53444bcfb0f2ffeebc1cbe460c68f7a6697#diff-637ad392e8ce75e51da570f00d28c0bbL126

Looking into it...

**Comment by vext01** [comment]
I had to manually remove the ykpack lines from the Cargo.lock file and re-run `cargo check` to get the newer commit hash for it. I don't  know why.

Also found a bogus line in `extdeps.rs`. This may be the cause, but I don't know for sure. Let's keep a close eye on this...

OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
Missed a substitution in a test:
```
failures:
---- [run-make] run-make/yk-tir-section stdout ----
error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
LD_LIBRARY_PATH="/home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/test/run-make/yk-tir-section/yk-tir-section:/home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/stage2/lib:/home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/stage0/lib" '/home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/test/run-make/yk-tir-section/yk-tir-section -L /home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/test/run-make/yk-tir-section/yk-tir-section  tir_sec.rs
# Exit non-zero if there was no Yorick TIR section in the binary.
[ "`readelf --section-headers /home/buildbot-worker7/worker7/buildbot-build-script/build/build/x86_64-unknown-linux-gnu/test/run-make/yk-tir-section/yk-tir-section/tir_sec | grep yk_tir | wc -l`" != 0 ]
Makefile:4: recipe for target 'all' failed
```

Testing the fix now.

**Comment by vext01** [comment]
If you are OK with the last push, I'll squash.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Splat.

**Pull request merged**
