### PR TITLE
ykpack tidy

### PR DESCRIPTION
**Pull request by ltratt**
ci-yk: ltratt ykpack_tidy

### CODE REVIEW

**Comment by vext01** [comment]
this is fine.

bors r+

**Comment by ltratt** [comment]
Mea culpa! I keep forgetting that `x.py fmt` works now. OK to squash?

**Comment by vext01** [comment]
You just need to run `./x.py fmt`.

**Comment by vext01** [comment]
Oops. Yes please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
