### PR TITLE
Compiler Support for Trace Inputs

### PR DESCRIPTION
**Pull request by vext01**
As discussed.

There is a ykpack change coming too...

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good!

**Comment by vext01** [comment]
I'll prime the CI...

**Comment by ptersilie** [comment]
Please do.

**Comment by ptersilie** [comment]
Companion PR is merged. So once you remove the priming commit I will merge.

**Comment by vext01** [comment]
Done. Also updated lock. Hope you don't mind.

**Comment by ptersilie** [comment]
I don't.

bors r+

**Pull request merged**
