### PR TITLE
Compiler support for trace trimming.

### PR DESCRIPTION
**Pull request by vext01**
When serialising the SIR, we set flags for items marked `#[trace_head]`
and `#[trace_tail]`.

For more info, see:
https://github.com/softdevteam/yk/pull/26

Again, this forms a CI cycle. We need to discuss before merging.

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good to me.

**Comment by ltratt** [comment]
Fine with me too.

**Comment by vext01** [comment]
We can now `r+`. The commit I just pushed breaks the cycle and will be reverted later.

**Comment by ltratt** [comment]
Reverted in a later PR?

**Comment by vext01** [comment]
Yes, after this PR comes the ykpack companion PR, then we have to flip back the `ykpack` dependency to use the new ykpack.

Makes sense?

**Comment by ltratt** [comment]
Got it.

bors r+

**Comment by vext01** [comment]
If you are OK with that latest push, please retry. I think it should stay separate.

**Pull request merged**
