### PR TITLE
Adjust the opt-level for tracing as neccesary. 

### PR DESCRIPTION
**Pull request by vext01**
The first commit is the meat, the second is sneaked in. See commit messages.

Raising as a draft while I check the performance is similar before and after.

### CODE REVIEW

**Comment by vext01** [comment]
bors r-

Woah there!

> Raising as a draft while I check the performance is similar before and after.

**Comment by ltratt** [comment]
Oops!

**Comment by vext01** [comment]
Performance is unchanged, which is good.

Please go ahead.

**Comment by vext01** [comment]
I forgot we had a test for this functionality. Fixing...

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
