### PR TITLE
Refs and tuples

### PR DESCRIPTION
**Pull request by vext01**
Needed for https://github.com/softdevteam/yk/pull/94

### CODE REVIEW

**Comment by vext01** [comment]
uh... what's the deal with all of this CI?

**Comment by ptersilie** [comment]
Looks fine. Please squash and add yk dependency commit.

**Comment by vext01** [comment]
bors try

**Comment by ptersilie** [comment]
https://github.com/softdevteam/yk/pull/94 merged. Let's remove the primer and merge this too.

**Comment by vext01** [comment]
Priming removed. Cargo.lock updated.

Ready for merge without squashing.

**Pull request merged**
