### PR TITLE
Remove our sole in-compiler SIR test.

### PR DESCRIPTION
**Pull request by vext01**
Since we are having a cleanup of ykrustc, this has been bugging me for some time. See commit message.

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]

**Comment by vext01** [comment]
Are you able to run bors? I may need to fiddle some settings if not.

**Comment by bjorn3** [comment]
I am pretty sure bors will not accept me, but I can try:

bors r+

**Comment by vext01** [comment]
Try now.

**Comment by bjorn3** [comment]
It works. Thanks!

**Comment by vext01** [comment]
I had to grant you the "write" role to the repo to allow bors.

**Comment by vext01** [comment]
Missed some stuff. Fixing.

**Comment by vext01** [comment]
OK to squash?

**Comment by bjorn3** [comment]
Sure

**Comment by vext01** [comment]
splat.

**Comment by bjorn3** [comment]
I confirmed that this makes the diff of compiletest against upstream empty.

bors r+

**Comment by vext01** [comment]
> I confirmed that this makes the diff of compiletest against upstream empty.

I also did that :)

**Pull request merged**
