### PR TITLE
Parallel CI

### PR DESCRIPTION
**Pull request by vext01**
~~Testing. Please do not review.~~

This should now work. I'm interested to see how long the build takes when running in parallel.

If all goes to plan, I'll have another PR for the bulidbot config repo.

### CODE REVIEW

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
To clarify, this is now ready for review.

**Comment by vext01** [comment]
We can start bors on this now.

**Comment by bjorn3** [comment]
The build log link gives a connection reinitialized error.

**Comment by vext01** [comment]
```
---- net::tcp::tests::fast_rebind stdout ----
thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Address already in use (os error 98)', src/libstd/net/tcp.rs:1283:13
```

This is most unfortunate. Could it be that one of the builds binds an address and the other build also tries to, but fails?

**Comment by vext01** [comment]
Possible solutions:
 * Add a sleep to the start to one of the builds so as to attempt to avoid test clashing.
 * Retry the tests in a loop (already passing suites should be skipped)
 * A proper fix

I think this is worthy of an upstream bug report nonetheless.

**Comment by ltratt** [comment]
> Could it be that one of the builds binds an address and the other build also tries to, but fails?

Sounds plausible. I think the onus is on us to fix/update the test, however.

If you look at https://github.com/rust-lang/rust/blob/master/src/libstd/net/test.rs#L35 (the `base_port`) function, you can see that there's an attempt to avoid this problem, but it doesn't seem to fully work. I think that's where I'd focus our efforts on, at least at first.

**Comment by vext01** [comment]
> If you look at...

Ah, nice find. Yes, I see why this doesn't work for us. Watch this space.

**Comment by vext01** [comment]
That last push should fix it.

OK?

**Comment by ltratt** [comment]
Fine with me. Can you reword the commit title to remove the extraneous "for"? Then I can start bors.

**Comment by ltratt** [comment]
Fine with me. Can you reword the commit title to remove the extraneous "for"? Then I can start bors.

**Comment by vext01** [comment]
Oops. It was supposed to be "from" not "for". Fixed.

**Comment by ltratt** [comment]
I wonder why we got a timeout and then success?

**Comment by bjorn3** [comment]
I think that timeout is for the try from https://github.com/softdevteam/ykrustc/pull/49#issuecomment-534021015 which got issued 9 hours ago.

**Comment by ltratt** [comment]
That had not occurred to me as a possibility -- good spot!

**Pull request merged**
