### PR TITLE
Fixes due to changes in ykpack::Local.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/softdevteam/yk/pull/32

### CODE REVIEW

**Comment by ltratt** [comment]
This looks OK to me. Please add the cycle breaker commit.

**Comment by vext01** [comment]
Cycle breaker locked and loaded.

**Comment by vext01** [comment]
Investigating test failures.

**Comment by vext01** [comment]
All tests passing now. OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Splat.

**Pull request merged**
