### PR TITLE
Add lowerings for StorageLive/StorageDead

### PR DESCRIPTION
**Pull request by ptersilie**
Companion PR for https://github.com/softdevteam/yk/pull/61

### CODE REVIEW

**Comment by ptersilie** [comment]
@vext01 This needs a rebase and a 3-way merge, once you approved the PR.

**Comment by vext01** [comment]
This is fine.

**Comment by ptersilie** [comment]
I've added a commit that allows us to manually build a version of `ykrustc` which we can use to merge softdevteam/yk#61. After that's merged we can undo this commit, and merge this PR.

**Comment by ptersilie** [comment]
bors try

**Comment by ptersilie** [comment]
It didn't push properly.

bors try

**Comment by ptersilie** [comment]
Good, this is ready for squashing and merging.

**Comment by vext01** [comment]
Please squash

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
