### PR TITLE
Yk Reset

### PR DESCRIPTION
**Pull request by vext01**
This discards all of our changes to upstream rust, syncs us to today's upstream rust, and puts back select few bits that are required for CI.

The last 5 commits are reviewable, the first of which has a descriptive commit message explaining our decision to do this.

### CODE REVIEW

**Comment by ltratt** [comment]
This all looks OK with one minor proviso: I'm now going to be picky about our use of "bitcode" and "IR" w.r.t. LLVM. We're using LLVM IR: LLVM bitcode is just the serialisation mechanism for that IR. The commit message for https://github.com/softdevteam/ykrustc/pull/182/commits/79a611b3d37c4140bad90e8843d49fbb5dadb094 thus needs a slight tweak. Please feel free to force push an update.

**Comment by vext01** [comment]
Corrected. Ready for bors.

**Comment by ltratt** [comment]
I like the commit message -- ignoring my minor change request, I think you've expressed yourself elegantly, and captured what both I and @ptersilie also feel. That said... onwards and upwards!

bors r+

**Comment by vext01** [comment]
Thanks. It seemed like a moment in time that deserved a certain amount of respect 😄

**Comment by ptersilie** [comment]
Nicely put @vext01.

**Pull request merged**
