### PR TITLE
SerU128 was removed from ykpack.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/softdevteam/yk/pull/207.

~~ci-yk: vext01 rm-ser128~~

### CODE REVIEW

**Comment by ptersilie** [comment]
bors try

**Comment by vext01** [comment]
I prematurely removed the yk branch!

I suppose what we should really be doing is removing the `ci-yk` line so as to test master! I'll do that now.

**Comment by vext01** [comment]
Done, please try again.

**Pull request merged**
