### PR TITLE
Insert TraceDebugCall terminators when yktrace::trace_debug is used.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/softdevteam/yk/pull/152

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good. Please prime.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try -

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by ptersilie** [comment]
Companion PR is merged. Let's remove the priming stuff.

**Comment by vext01** [comment]
Priming removed, and squashed.

**Pull request merged**
