### PR TITLE
Require `interp_step` to return `bool`.

### PR DESCRIPTION
**Pull request by ptersilie**
ci-yk: ptersilie trace_stitching_tir

### CODE REVIEW

**Comment by vext01** [comment]
LGTM.

bors r+

**Comment by bjorn3** [comment]
bors r- retry

Depends on softdevteam/yk#289.

**Comment by ptersilie** [comment]
I think this should be fine. I've added the dependency in the PR message (which is our new way of resolving dependency cycles).

**Comment by ltratt** [comment]
I think @bjorn3's implicit point is that we merge this *before* the corresponding yk PR is ready, we'll have a cached ykrustc which might not be able to compile other yk PRs which might be raised and merged before we merge trace_stitching_tir.

**Comment by ptersilie** [comment]
Yeah, let's get the yk PR ready first.

**Comment by vext01** [comment]
Yes, I should have reviewed the other PR first. My bad.

**Comment by vext01** [comment]
This is ready to go?

**Comment by ptersilie** [comment]
Yes.

**Comment by vext01** [comment]
Some tests failed.

**Comment by ptersilie** [comment]
Fixed.

**Comment by vext01** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed!

**Comment by ptersilie** [comment]
Accidentally pushed `Cargo.toml` and `Cargo.lock`. Fixed, please try again.

**Pull request merged**
