### PR TITLE
Move some code to ykpack

### PR DESCRIPTION
**Pull request by bjorn3**
Accompanying PR to https://github.com/softdevteam/yk/pull/230.

### CODE REVIEW

**Comment by vext01** [comment]
This LGTM.

Let's wait for the yk side to be merged first.

**Comment by vext01** [comment]
We need to kill the `yk-ci` I think?

**Comment by bjorn3** [comment]
Removed

**Comment by vext01** [comment]
Just rustfmt now

**Comment by bjorn3** [comment]
Rustfmt'ed and squashed into 99bf900 to form f0fdd6b. (/me forgot about the squash rule again...)

**Pull request merged**
